#######################################################################
#                          ShyCommandSigns                            #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  shycommandsigns:
    aliases:
      - "scsign"
