#######################################################################
#                          ShyCommandSigns                            #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  shycommandsigns:
    aliases:
      - "scsign"


############################
# Global Sign Settings
############################
global:
  # How often a clicks on signs are registered.
  clickCooldownTicks: 30
